// src/lib/expandedCatalog.ts
// Expanded Product Catalog - 100+ Hardware Products
// Comprehensive database for scaling DXM369 to full marketplace

import { DealRadarItem } from "@/lib/dealRadar";

// 🎮 EXPANDED GPU CATALOG (30+ Models)
export const expandedGpuCatalog: Omit<DealRadarItem, 'dxmScore'>[] = [
  // RTX 40 Series - High End
  {
    id: "gpu-rtx4090-asus-tuf",
    asin: "B0BHQ6CQZV",
    title: "ASUS TUF Gaming GeForce RTX 4090 OC Edition",
    brand: "ASUS",
    category: "gpu",
    price: 1699,
    previousPrice: 1799,
    vram: "24GB GDDR6X",
    tdp: "450W",
    boostClock: "2.61 GHz",
    baseClock: "2.23 GHz",
    imageUrl: "/images/gpus/rtx4090.svg",
    domain: "com",
    tags: ["4k", "flagship", "content-creation", "overclocked"],
    trend: [1799, 1779, 1749, 1719, 1699],
    availability: "In Stock",
    primeEligible: false,
    vendor: "Amazon",
  },
  
  {
    id: "gpu-rtx4090-msi-suprim",
    asin: "B0BG9Z9Q5M",
    title: "MSI GeForce RTX 4090 SUPRIM X 24GB",
    brand: "MSI",
    category: "gpu",
    price: 1749,
    previousPrice: 1899,
    vram: "24GB GDDR6X",
    tdp: "450W",
    boostClock: "2.64 GHz",
    baseClock: "2.23 GHz",
    imageUrl: "/images/gpus/rtx4090.svg",
    domain: "com",
    tags: ["4k", "flagship", "premium", "rgb"],
    trend: [1899, 1849, 1799, 1774, 1749],
    availability: "Limited Stock",
    primeEligible: false,
    vendor: "Amazon",
  },

  {
    id: "gpu-rtx4080-super-gigabyte",
    asin: "B0CS19F7VD",
    title: "Gigabyte GeForce RTX 4080 SUPER Gaming OC",
    brand: "Gigabyte",
    category: "gpu",
    price: 1049,
    previousPrice: 1199,
    vram: "16GB GDDR6X",
    tdp: "320W",
    boostClock: "2.58 GHz",
    baseClock: "2.20 GHz",
    imageUrl: "/images/products/gpus/msi_rtx4080super_gaming.svg",
    domain: "com",
    tags: ["4k", "premium", "overclocked"],
    trend: [1199, 1149, 1099, 1074, 1049],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "gpu-rtx4070ti-super-evga",
    asin: "B0CFRW9Z9D",
    title: "EVGA GeForce RTX 4070 Ti SUPER FTW3",
    brand: "EVGA",
    category: "gpu",
    price: 849,
    previousPrice: 949,
    vram: "16GB GDDR6X",
    tdp: "285W",
    boostClock: "2.64 GHz",
    baseClock: "2.34 GHz",
    imageUrl: "/images/gpus/rtx4070ti-s-evga.png",
    domain: "com",
    tags: ["1440p", "4k-capable", "overclocked"],
    trend: [949, 919, 889, 869, 849],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  // AMD RX 7000 Series
  {
    id: "gpu-rx7900xtx-sapphire-nitro",
    asin: "B0CFHX9JTX",
    title: "Sapphire Nitro+ AMD Radeon RX 7900 XTX",
    brand: "Sapphire",
    category: "gpu",
    price: 899,
    previousPrice: 1099,
    vram: "24GB GDDR6",
    tdp: "355W",
    boostClock: "2.68 GHz",
    baseClock: "1.93 GHz",
    imageUrl: "/images/gpus/rx7900xtx-sapphire.png",
    domain: "com",
    tags: ["4k", "high-vram", "amd-flagship"],
    trend: [1099, 1049, 999, 949, 899],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "gpu-rx7900xt-powercolor-red-devil",
    asin: "B0CFHX8KTY",
    title: "PowerColor Red Devil AMD Radeon RX 7900 XT",
    brand: "PowerColor",
    category: "gpu",
    price: 749,
    previousPrice: 899,
    vram: "20GB GDDR6",
    tdp: "315W",
    boostClock: "2.54 GHz",
    baseClock: "1.50 GHz",
    imageUrl: "/images/gpus/rx7900xt-powercolor.png",
    domain: "com",
    tags: ["4k", "high-vram", "overclocked"],
    trend: [899, 869, 829, 789, 749],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  // Budget & Mid-Range Options
  {
    id: "gpu-rtx4060ti-16gb-asus",
    asin: "B0C7CGMZ6U",
    title: "ASUS Dual GeForce RTX 4060 Ti 16GB OC",
    brand: "ASUS",
    category: "gpu",
    price: 479,
    previousPrice: 549,
    vram: "16GB GDDR6",
    tdp: "165W",
    boostClock: "2.54 GHz",
    baseClock: "2.31 GHz",
    imageUrl: "/images/gpus/rtx4060ti-16gb-asus.png",
    domain: "com",
    tags: ["1080p", "1440p", "high-vram"],
    trend: [549, 529, 509, 494, 479],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "gpu-rx6700xt-asrock-challenger",
    asin: "B08YP4R3N7",
    title: "ASRock Challenger AMD Radeon RX 6700 XT",
    brand: "ASRock",
    category: "gpu",
    price: 329,
    previousPrice: 479,
    vram: "12GB GDDR6",
    tdp: "230W",
    boostClock: "2.58 GHz",
    baseClock: "2.42 GHz",
    imageUrl: "/images/gpus/rx6700xt-asrock.png",
    domain: "com",
    tags: ["1440p", "value", "high-vram", "previous-gen"],
    trend: [479, 429, 389, 359, 329],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  // Previous Generation Value Options
  {
    id: "gpu-rtx3070-zotac-twin-edge",
    asin: "B08L8L71LS",
    title: "Zotac Gaming GeForce RTX 3070 Twin Edge OC",
    brand: "Zotac",
    category: "gpu",
    price: 449,
    previousPrice: 599,
    vram: "8GB GDDR6",
    tdp: "220W",
    boostClock: "1.73 GHz",
    baseClock: "1.50 GHz",
    imageUrl: "/images/gpus/rtx3070-zotac.png",
    domain: "com",
    tags: ["1440p", "value", "previous-gen", "ray-tracing"],
    trend: [599, 569, 529, 489, 449],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "gpu-rtx3060ti-msi-gaming-x",
    asin: "B08P2C6JKV",
    title: "MSI Gaming GeForce RTX 3060 Ti Gaming X",
    brand: "MSI",
    category: "gpu",
    price: 379,
    previousPrice: 499,
    vram: "8GB GDDR6",
    tdp: "200W",
    boostClock: "1.70 GHz",
    baseClock: "1.41 GHz",
    imageUrl: "/images/gpus/rtx3060ti-msi.png",
    domain: "com",
    tags: ["1080p", "1440p", "value", "previous-gen"],
    trend: [499, 469, 429, 404, 379],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  }
];

// ⚡ EXPANDED CPU CATALOG (25+ Models)
export const expandedCpuCatalog: Omit<DealRadarItem, 'dxmScore'>[] = [
  // Intel 14th Gen High-End
  {
    id: "cpu-i9-14900ks",
    asin: "B0CHBDJ9N8",
    title: "Intel Core i9-14900KS Desktop Processor",
    brand: "Intel",
    category: "cpu",
    price: 699,
    previousPrice: 799,
    cores: "24",
    threads: "32",
    baseClock: "3.2 GHz",
    boostClock: "6.0 GHz",
    imageUrl: "/images/cpus/i9-14900ks.png",
    domain: "com",
    tags: ["gaming", "flagship", "overclocking", "special-edition"],
    trend: [799, 779, 749, 724, 699],
    availability: "Limited Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "cpu-i7-14700kf",
    asin: "B0CHBD4Q5S",
    title: "Intel Core i7-14700KF Desktop Processor",
    brand: "Intel",
    category: "cpu",
    price: 369,
    previousPrice: 429,
    cores: "20",
    threads: "28",
    baseClock: "3.4 GHz",
    boostClock: "5.6 GHz",
    imageUrl: "/images/cpus/i7-14700kf.png",
    domain: "com",
    tags: ["gaming", "productivity", "no-igpu", "value"],
    trend: [429, 409, 389, 379, 369],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "cpu-i5-14600kf",
    asin: "B0CHBD3Y8Z",
    title: "Intel Core i5-14600KF Desktop Processor",
    brand: "Intel",
    category: "cpu",
    price: 269,
    previousPrice: 319,
    cores: "14",
    threads: "20",
    baseClock: "3.5 GHz",
    boostClock: "5.3 GHz",
    imageUrl: "/images/cpus/i5-14600kf.png",
    domain: "com",
    tags: ["gaming", "mainstream", "no-igpu", "overclocking"],
    trend: [319, 309, 289, 279, 269],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  // AMD Ryzen 7000 X3D Series
  {
    id: "cpu-ryzen-9-7950x3d",
    asin: "B0BTZB7F90",
    title: "AMD Ryzen 9 7950X3D Gaming Processor",
    brand: "AMD",
    category: "cpu",
    price: 599,
    previousPrice: 749,
    cores: "16",
    threads: "32",
    baseClock: "4.2 GHz",
    boostClock: "5.7 GHz",
    imageUrl: "/images/cpus/ryzen-9-7950x3d.png",
    domain: "com",
    tags: ["gaming", "3d-cache", "flagship", "productivity"],
    trend: [749, 719, 679, 639, 599],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "cpu-ryzen-7-7700x",
    asin: "B0BBHD5D9Y",
    title: "AMD Ryzen 7 7700X Desktop Processor",
    brand: "AMD",
    category: "cpu",
    price: 299,
    previousPrice: 399,
    cores: "8",
    threads: "16",
    baseClock: "4.5 GHz",
    boostClock: "5.4 GHz",
    imageUrl: "/images/cpus/ryzen-7-7700x.png",
    domain: "com",
    tags: ["gaming", "productivity", "mainstream", "am5"],
    trend: [399, 379, 349, 324, 299],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  // Budget Options
  {
    id: "cpu-i5-14400f",
    asin: "B0CHBD3Y9Z",
    title: "Intel Core i5-14400F Desktop Processor",
    brand: "Intel",
    category: "cpu",
    price: 189,
    previousPrice: 229,
    cores: "10",
    threads: "16",
    baseClock: "2.5 GHz",
    boostClock: "4.7 GHz",
    imageUrl: "/images/cpus/i5-14400f.png",
    domain: "com",
    tags: ["gaming", "budget", "value", "no-igpu"],
    trend: [229, 219, 209, 199, 189],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "cpu-ryzen-5-7500f",
    asin: "B0BBHD5E8Z",
    title: "AMD Ryzen 5 7500F Desktop Processor",
    brand: "AMD",
    category: "cpu",
    price: 179,
    previousPrice: 219,
    cores: "6",
    threads: "12",
    baseClock: "3.7 GHz",
    boostClock: "5.0 GHz",
    imageUrl: "/images/cpus/ryzen-5-7500f.png",
    domain: "com",
    tags: ["gaming", "budget", "value", "am5"],
    trend: [219, 209, 199, 189, 179],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  }
];

// 💻 EXPANDED LAPTOP CATALOG (20+ Models)
export const expandedLaptopCatalog: Omit<DealRadarItem, 'dxmScore'>[] = [
  // Gaming Laptops - High End
  {
    id: "laptop-asus-rog-strix-scar-18",
    asin: "B0C7CGMZ7V",
    title: "ASUS ROG Strix SCAR 18 Gaming Laptop RTX 4090",
    brand: "ASUS",
    category: "laptop",
    price: 3299,
    previousPrice: 3799,
    memory: "32GB DDR5",
    storage: "2TB SSD",
    cores: "Intel i9-13980HX",
    display: "18\" QHD 240Hz",
    imageUrl: "/images/laptops/rog-strix-g16.svg",
    domain: "com",
    tags: ["gaming", "flagship", "rtx-4090", "240hz", "desktop-replacement"],
    trend: [3799, 3649, 3499, 3399, 3299],
    availability: "In Stock",
    primeEligible: false,
    vendor: "Amazon",
  },

  {
    id: "laptop-msi-ge78-raider",
    asin: "B0C9XQMZ5U",
    title: "MSI GE78 Raider Gaming Laptop RTX 4080",
    brand: "MSI",
    category: "laptop",
    price: 2799,
    previousPrice: 3199,
    memory: "32GB DDR5",
    storage: "1TB SSD",
    cores: "Intel i9-13950HX",
    display: "17.3\" QHD 240Hz",
    imageUrl: "/images/laptops/rog-strix-g16.svg",
    domain: "com",
    tags: ["gaming", "premium", "rtx-4080", "240hz", "rgb"],
    trend: [3199, 3049, 2899, 2849, 2799],
    availability: "In Stock",
    primeEligible: false,
    vendor: "Amazon",
  },

  // Mid-Range Gaming
  {
    id: "laptop-hp-omen-16-rtx4060",
    asin: "B0BWQKQZX0",
    title: "HP OMEN 16 Gaming Laptop RTX 4060",
    brand: "HP",
    category: "laptop",
    price: 1199,
    previousPrice: 1399,
    memory: "16GB DDR5",
    storage: "512GB SSD",
    cores: "Intel i7-13700HX",
    display: "16.1\" FHD 165Hz",
    imageUrl: "/images/placeholder-laptop.svg",
    domain: "com",
    tags: ["gaming", "mainstream", "rtx-4060", "165hz"],
    trend: [1399, 1349, 1299, 1249, 1199],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "laptop-acer-nitro-5-rtx4050",
    asin: "B0BWQKR0X1",
    title: "Acer Nitro 5 Gaming Laptop RTX 4050",
    brand: "Acer",
    category: "laptop",
    price: 899,
    previousPrice: 1099,
    memory: "16GB DDR4",
    storage: "512GB SSD",
    cores: "AMD Ryzen 7 7735HS",
    display: "15.6\" FHD 144Hz",
    imageUrl: "/images/laptops/acer-nitro-5.png",
    domain: "com",
    tags: ["gaming", "budget", "rtx-4050", "144hz", "value"],
    trend: [1099, 1049, 999, 949, 899],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  // Productivity & Creative
  {
    id: "laptop-macbook-pro-16-m3-max",
    asin: "B0CM5JV269",
    title: "Apple MacBook Pro 16-inch M3 Max",
    brand: "Apple",
    category: "laptop",
    price: 3199,
    previousPrice: 3499,
    memory: "36GB Unified Memory",
    storage: "1TB SSD",
    cores: "M3 Max (14-core CPU)",
    display: "16.2\" Liquid Retina XDR",
    imageUrl: "/images/laptops/macbook-pro-16-m3-max.png",
    domain: "com",
    tags: ["productivity", "creative", "premium", "m3-max", "macos"],
    trend: [3499, 3399, 3299, 3249, 3199],
    availability: "In Stock",
    primeEligible: false,
    vendor: "Amazon",
  },

  {
    id: "laptop-dell-xps-15-oled",
    asin: "B0B9LBQZX8",
    title: "Dell XPS 15 OLED Laptop Intel i7 RTX 4050",
    brand: "Dell",
    category: "laptop",
    price: 1899,
    previousPrice: 2199,
    memory: "32GB LPDDR5",
    storage: "1TB SSD",
    cores: "Intel i7-13700H",
    display: "15.6\" OLED 3.5K",
    imageUrl: "/images/laptops/dell-xps-15-oled.png",
    domain: "com",
    tags: ["productivity", "creative", "oled", "premium"],
    trend: [2199, 2099, 1999, 1949, 1899],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  // Business & Ultrabooks
  {
    id: "laptop-surface-laptop-5",
    asin: "B0B1SJFB3L",
    title: "Microsoft Surface Laptop 5 Intel i7",
    brand: "Microsoft",
    category: "laptop",
    price: 1399,
    previousPrice: 1699,
    memory: "16GB LPDDR5",
    storage: "512GB SSD",
    cores: "Intel i7-1255U",
    display: "13.5\" PixelSense",
    imageUrl: "/images/laptops/surface-laptop-5.png",
    domain: "com",
    tags: ["business", "ultrabook", "touchscreen", "premium"],
    trend: [1699, 1649, 1549, 1474, 1399],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  }
];

// 🖥️ NEW CATEGORIES - MONITORS
export const monitorCatalog: Omit<DealRadarItem, 'dxmScore'>[] = [
  {
    id: "monitor-lg-27gp950-b",
    asin: "B094RWMX9G",
    title: "LG 27GP950-B 27\" 4K 144Hz Gaming Monitor",
    brand: "LG",
    category: "monitor",
    price: 599,
    previousPrice: 799,
    memory: "4K UHD",
    storage: "144Hz",
    cores: "Nano IPS",
    display: "27\" 4K 144Hz HDR600",
    imageUrl: "/images/monitors/lg-27gp950.png",
    domain: "com",
    tags: ["4k", "144hz", "gaming", "hdr", "nano-ips"],
    trend: [799, 749, 699, 649, 599],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "monitor-samsung-odyssey-g7",
    asin: "B088HJ4VQK",
    title: "Samsung Odyssey G7 32\" 1440p 240Hz Curved",
    brand: "Samsung",
    category: "monitor",
    price: 549,
    previousPrice: 699,
    memory: "QHD",
    storage: "240Hz",
    cores: "VA Panel",
    display: "32\" 1440p 240Hz Curved",
    imageUrl: "/images/monitors/samsung-odyssey-g7.png",
    domain: "com",
    tags: ["1440p", "240hz", "curved", "gaming", "va-panel"],
    trend: [699, 669, 619, 584, 549],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  }
];

// 💾 SSD STORAGE CATALOG
export const ssdCatalog: Omit<DealRadarItem, 'dxmScore'>[] = [
  {
    id: "ssd-samsung-980-pro-2tb",
    asin: "B08RK2SR23",
    title: "Samsung 980 PRO 2TB PCIe 4.0 NVMe SSD",
    brand: "Samsung",
    category: "ssd",
    price: 149,
    previousPrice: 199,
    memory: "2TB",
    storage: "PCIe 4.0",
    cores: "7000 MB/s",
    display: "M.2 2280",
    imageUrl: "/images/placeholder-gpu.svg",
    domain: "com",
    tags: ["nvme", "pcie-4", "high-speed", "gaming"],
    trend: [199, 189, 169, 159, 149],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  },

  {
    id: "ssd-wd-black-sn850x-1tb",
    asin: "B0B7CQ2CHH",
    title: "WD Black SN850X 1TB PCIe 4.0 Gaming SSD",
    brand: "Western Digital",
    category: "ssd",
    price: 79,
    previousPrice: 119,
    memory: "1TB",
    storage: "PCIe 4.0",
    cores: "7300 MB/s",
    display: "M.2 2280",
    imageUrl: "/images/placeholder-gpu.svg",
    domain: "com",
    tags: ["nvme", "pcie-4", "gaming", "value"],
    trend: [119, 109, 99, 89, 79],
    availability: "In Stock",
    primeEligible: true,
    vendor: "Amazon",
  }
];

// Combine all catalogs for easy access
export const expandedProductCatalog = {
  gpu: expandedGpuCatalog,
  cpu: expandedCpuCatalog,
  laptop: expandedLaptopCatalog,
  monitor: monitorCatalog,
  ssd: ssdCatalog
};

// Get total product count
export const getTotalProductCount = (): number => {
  return Object.values(expandedProductCatalog).reduce((total, catalog) => total + catalog.length, 0);
};

// Get products by category with DXM scoring
export const getExpandedCatalogByCategory = (category: keyof typeof expandedProductCatalog) => {
  return expandedProductCatalog[category] || [];
};
