#!/usr/bin/env ts-node
// scripts/generate-seo-page.ts
// SEO Page Generator Script
// Auto-generates SEO-optimized pages for DXM369

import * as fs from 'fs';
import * as path from 'path';

interface SEOPageConfig {
  title: string;
  description: string;
  keywords: string[];
  category: 'storage' | 'laptop' | 'monitor' | 'gpu' | 'cpu';
  trackingId: string;
  slug: string;
  h1: string;
  intro: string;
  sections: {
    title: string;
    description: string;
    trackingContext?: {
      source?: string;
      intent?: string;
    };
  }[];
}

const TEMPLATE = `// src/app/{SLUG}/page.tsx
// SEO-Optimized Landing Page: {TITLE}
// Auto-generated by generate-seo-page.ts

import { {GET_DEALS_FUNCTION} } from "@/lib/dealRadar";
import { DealCard } from "@/components/DealCard";
import { generateBreadcrumbStructuredData } from "@/lib/seo";
import type { Metadata } from "next";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "{TITLE} | DXM369",
  description: "{DESCRIPTION}",
  keywords: {KEYWORDS},
  openGraph: {
    title: "{TITLE}",
    description: "{DESCRIPTION}",
    url: "/{SLUG}",
  },
  alternates: {
    canonical: "https://dxm369.com/{SLUG}",
  },
};

export default async function {COMPONENT_NAME}() {
  const allDeals = await {GET_DEALS_FUNCTION}();
  
  // Filter deals by category/price range if needed
  const relevantDeals = allDeals.filter(deal => 
    deal.category === "{CATEGORY}" || deal.category === "{CATEGORY}"
  );
  
  // Generate breadcrumb structured data
  const breadcrumbData = generateBreadcrumbStructuredData([
    { name: "Home", url: "/" },
    { name: "{CATEGORY_NAME}", url: "/{CATEGORY}" },
    { name: "{H1}", url: "/{SLUG}" }
  ]);

  return (
    <>
      {/* Breadcrumb Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(breadcrumbData),
        }}
      />
      
      <div className="min-h-screen py-6 relative">
        <div className="max-w-6xl mx-auto px-4">
          {/* SEO-Optimized Header */}
          <header className="glass-hero mb-8 p-8 clip-corner-tl glass-corner-accent holographic-sheen">
            <div className="flex items-center gap-3 mb-4">
              <div className="h-2 w-2 bg-cyan-400 animate-neon-pulse shadow-[0_0_12px_cyan]" />
              <span className="text-[10px] font-mono uppercase tracking-[0.25em] text-cyan-400 font-bold">
                {TITLE}
              </span>
            </div>
            <h1 className="text-4xl font-bold text-white mb-4 uppercase tracking-tight">
              {H1}
            </h1>
            <p className="text-slate-400 font-mono leading-relaxed border-l-2 border-cyan-500/40 pl-4 max-w-4xl mb-6">
              {INTRO}
            </p>
          </header>

{SECTIONS}

          {/* SEO Content Section */}
          <section className="glass-panel p-8 mb-8">
            <h2 className="text-xl font-bold text-white mb-4">How We Find the Best Deals</h2>
            <div className="prose prose-invert max-w-none">
              <p className="text-slate-300 mb-4">
                Our DXM Value Scoring system analyzes deals using a proprietary algorithm 
                that evaluates performance-per-dollar, deal quality, trust signals, and market trends.
              </p>
            </div>
          </section>

          {/* Call to Action */}
          <section className="glass-hero p-6 text-center">
            <h2 className="text-xl font-bold text-white mb-4">Ready to Find Your Perfect Deal?</h2>
            <p className="text-slate-400 mb-6">
              Browse our complete catalog with real-time DXM Value Scoring and affiliate links to the best deals.
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <a 
                href="/{CATEGORY}" 
                className="glass-panel px-6 py-3 text-cyan-400 hover:text-cyan-300 font-semibold transition-colors"
              >
                View All {CATEGORY_NAME} →
              </a>
              <a 
                href="/trending" 
                className="glass-panel-secondary px-6 py-3 text-slate-300 hover:text-white font-semibold transition-colors"
              >
                Trending Deals
              </a>
            </div>
          </section>
        </div>
      </div>
    </>
  );
}
`;

function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function generateComponentName(slug: string): string {
  return slug
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('') + 'Page';
}

function getDealsFunction(category: string): string {
  const map: Record<string, string> = {
    storage: 'getDealsByCategory("ssd")',
    ssd: 'getDealsByCategory("ssd")',
    laptop: 'getLaptopDeals',
    monitor: 'getDealsByCategory("monitor")',
    gpu: 'getGpuDeals',
    cpu: 'getCpuDeals',
  };
  return map[category.toLowerCase()] || 'getDealsByCategory("' + category + '")';
}

function getCategoryName(category: string): string {
  const map: Record<string, string> = {
    storage: 'Storage',
    ssd: 'Storage',
    laptop: 'Laptops',
    monitor: 'Gaming Monitors',
    gpu: 'GPUs',
    cpu: 'CPUs',
  };
  return map[category.toLowerCase()] || category;
}

function generateSection(section: SEOPageConfig['sections'][0], index: number): string {
  const trackingSource = section.trackingContext?.source || 'seo';
  const intent = section.trackingContext?.intent || 'top10';
  
  return `          {/* ${section.title} */}
          <section className="mb-12">
            <div className="flex items-center gap-3 mb-6">
              <h2 className="text-2xl font-bold text-white">${section.title}</h2>
            </div>
            <p className="text-slate-400 text-sm mb-6">
              ${section.description}
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {relevantDeals.slice(${index * 3}, ${(index + 1) * 3}).map((deal) => (
                <DealCard 
                  key={deal.id} 
                  deal={deal} 
                  source="${trackingSource}" 
                  intent="${intent}"
                />
              ))}
            </div>
          </section>

`;
}

function generatePage(config: SEOPageConfig): string {
  const slug = config.slug || generateSlug(config.title);
  const componentName = generateComponentName(slug);
  const getDealsFunc = getDealsFunction(config.category);
  const categoryName = getCategoryName(config.category);
  
  let sections = '';
  config.sections.forEach((section, index) => {
    sections += generateSection(section, index);
  });
  
  return TEMPLATE
    .replace(/{SLUG}/g, slug)
    .replace(/{TITLE}/g, config.title)
    .replace(/{DESCRIPTION}/g, config.description)
    .replace(/{KEYWORDS}/g, JSON.stringify(config.keywords))
    .replace(/{H1}/g, config.h1)
    .replace(/{INTRO}/g, config.intro)
    .replace(/{CATEGORY}/g, config.category)
    .replace(/{CATEGORY_NAME}/g, categoryName)
    .replace(/{GET_DEALS_FUNCTION}/g, getDealsFunc)
    .replace(/{COMPONENT_NAME}/g, componentName)
    .replace(/{SECTIONS}/g, sections);
}

// CLI Interface
if (require.main === module) {
  const args = process.argv.slice(2);
  
  if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
    console.log(`
DXM369 SEO Page Generator

Usage:
  ts-node scripts/generate-seo-page.ts <title> [options]

Options:
  --category <category>    Category: storage, laptop, monitor, gpu, cpu
  --slug <slug>           Custom URL slug (auto-generated from title if not provided)
  --description <desc>    Meta description
  --keywords <keywords>   Comma-separated keywords
  --intro <intro>         Page introduction text
  --tracking-id <id>      Tracking ID (auto-selected based on category if not provided)

Examples:
  ts-node scripts/generate-seo-page.ts "Best SSD for Gaming 2025" --category storage
  ts-node scripts/generate-seo-page.ts "Top 5 NVMe Upgrades" --category storage --slug "top-5-nvme-upgrades"
    `);
    process.exit(0);
  }
  
  const title = args[0];
  const categoryIndex = args.indexOf('--category');
  const slugIndex = args.indexOf('--slug');
  const descIndex = args.indexOf('--description');
  const keywordsIndex = args.indexOf('--keywords');
  const introIndex = args.indexOf('--intro');
  const trackingIdIndex = args.indexOf('--tracking-id');
  
  const category = categoryIndex >= 0 && args[categoryIndex + 1] 
    ? args[categoryIndex + 1] 
    : 'storage';
  
  const slug = slugIndex >= 0 && args[slugIndex + 1]
    ? args[slugIndex + 1]
    : generateSlug(title);
  
  const description = descIndex >= 0 && args[descIndex + 1]
    ? args[descIndex + 1]
    : `Find the best ${category} deals of 2025 with DXM Value Scoring. Real-time price tracking and affiliate links.`;
  
  const keywords = keywordsIndex >= 0 && args[keywordsIndex + 1]
    ? args[keywordsIndex + 1].split(',').map(k => k.trim())
    : [`best ${category} deals 2025`, `${category} discounts`, `${category} price tracker`];
  
  const intro = introIndex >= 0 && args[introIndex + 1]
    ? args[introIndex + 1]
    : `Discover the best ${category} deals of 2025 with our proprietary DXM Value Scoring system. We analyze performance-per-dollar, deal quality, and market trends to surface the cleanest deals.`;
  
  const trackingId = trackingIdIndex >= 0 && args[trackingIdIndex + 1]
    ? args[trackingIdIndex + 1]
    : `dxmatrix-${category === 'storage' ? 'storage' : category === 'laptop' ? 'laptops' : category === 'monitor' ? 'monitors' : category}-20`;
  
  const config: SEOPageConfig = {
    title,
    description,
    keywords,
    category: category as any,
    trackingId,
    slug,
    h1: title,
    intro,
    sections: [
      {
        title: 'Top Recommendations',
        description: `Our top picks for ${category} based on DXM Value Scoring.`,
        trackingContext: {
          source: 'seo',
          intent: 'top10',
        },
      },
      {
        title: 'Best Value Options',
        description: `Best value ${category} deals with excellent performance-per-dollar ratios.`,
        trackingContext: {
          source: 'seo',
          intent: 'deal',
        },
      },
    ],
  };
  
  const pageContent = generatePage(config);
  const filePath = path.join(process.cwd(), 'src', 'app', slug, 'page.tsx');
  const dirPath = path.dirname(filePath);
  
  // Create directory if it doesn't exist
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
  
  // Write file
  fs.writeFileSync(filePath, pageContent);
  
  console.log(`✅ SEO page generated: ${filePath}`);
  console.log(`📝 Title: ${title}`);
  console.log(`🔗 Slug: /${slug}`);
  console.log(`🏷️  Tracking ID: ${trackingId}`);
  console.log(`📦 Category: ${category}`);
  console.log(`\n🚀 Next steps:`);
  console.log(`   1. Review the generated page`);
  console.log(`   2. Add product data if needed`);
  console.log(`   3. Deploy to production`);
  console.log(`   4. Submit to Google Search Console`);
}

export { generatePage };
export type { SEOPageConfig };

